### ISSUE TITLE
Heur.AdvMK.B Virus found in ed-profit-scanner updater.exe

### ISSUE THREAD

**Issue by JanT83** [maca134/ed-profit-scanner#2]
First of; I love ED Profit Scanner and would like to keep using it, but... today Norton performed an idle scan while I was away from the PC. When I came back it reported a Heur.AdvMK.B Virus found in ...appdata\local\programs\ed-profit-scanner\updater.exe

Anyone else getting this? False alarm (I hope)?

**Comment by maca134** [comment]
Well all the source code in on git so you can build it yourself. Most of the updater code is here https://github.com/maca134/ed-profit-scanner/blob/master/updater/Updater/MainWindow.xaml.cs
